# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-21 11:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='author',
            field=models.ForeignKey(default=datetime.datetime(2017, 5, 21, 10, 59, 0, 922217, tzinfo=utc), on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='blog.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entry',
            name='body',
            field=models.TextField(default=datetime.datetime(2017, 5, 21, 10, 59, 38, 370972, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 5, 21, 10, 59, 52, 475518, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entry',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('public', '公开')], default='draft', max_length=8),
        ),
        migrations.AddField(
            model_name='entry',
            name='title',
            field=models.CharField(default=datetime.datetime(2017, 5, 21, 11, 0, 9, 826427, tzinfo=utc), max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2017, 5, 21, 11, 0, 23, 491577, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='mail',
            field=models.EmailField(default=datetime.datetime(2017, 5, 21, 11, 0, 46, 503571, tzinfo=utc), max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default=datetime.datetime(2017, 5, 21, 11, 0, 53, 628037, tzinfo=utc), max_length=32),
            preserve_default=False,
        ),
    ]
